[package]
name = "hello_extism_guest"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["cdylib"]

[dependencies]
bincode = "1.3.3"
extism-convert = "1.1.0"
extism-pdk = "1.0.1"
hello_extism_shared = { version = "0.1.0", path = "../shared" }
serde = "1.0.197"
