[workspace]
resolver = "2"

members = [
  "hello_extism/guest",
  "hello_extism/host",
  "hello_extism/shared",
  "hello_floem",
  "hello_gpui",
  "hello_macros/declarative",
  "hello_macros/procedural",
  "textview",
  "todo0",
]
