[package]
name = "hello_macros_procedural"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
manyhow = "0.11.0"
quote = "1.0.35"
syn = { version = "2.0.50", features = ["full", "fold"] }
