[package]
name = "todo0"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
dirs = "5.0.1"
rand = "0.8.5"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
