[package]
name = "shared_mem"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3", features = ["derive"] }
env_logger = "0.11.3"
libc = "0.2.153"
raw_sync = "0.1.5"
rmp = "0.8.12"
shared_memory = "0.12.4"
