[package]
name = "http_exp"
version = "0.1.0"
edition = "2021"

[dependencies]
http = "1.1.0"
isahc = "1.7.2"
reqwest = { version = "0.12.2", features = ["json"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
tokio = { version = "1.37.0", features = ["full"] }
